name: Release

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: harnicode/uss
  HELM_NAMESPACE: harnicode/charts

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  publish-helm-chart:
    runs-on: ubuntu-latest
    needs: build-and-push-docker
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Helm Version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          
          # Update Chart.yaml with the new version and appVersion
          sed -i "s/^version:.*/version: ${VERSION}/" charts/uss/Chart.yaml
          sed -i "s/^appVersion:.*/appVersion: \"${VERSION}\"/" charts/uss/Chart.yaml

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Log in to the Container registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Package and Push Helm Chart
        run: |
          helm dependency update charts/uss
          helm package charts/uss --version ${{ env.VERSION }} --app-version ${{ env.VERSION }}
          helm push uss-${{ env.VERSION }}.tgz oci://${{ env.REGISTRY }}/${{ env.HELM_NAMESPACE }}
